version: '3.8'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:15.11.4-ce.0'
    container_name: gitlab
    restart: unless-stopped
    # hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - 0.0.0.0:8080:80
      # - 0.0.0.0:443:443
      - 0.0.0.0:2020:22
    volumes:
      - $HOME/gitlab/etc:/etc/gitlab
      - $HOME/gitlab/log:/var/log/gitlab
      - $HOME/gitlab/opt:/var/opt/gitlab
